spring.application.name=taskmanager


#H2 DB Configurator
spring.datasource.url=jdbc:h2:mem:taskdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password

# JPA Configuration

# NOTE: Update for local data only. For production, there are other tools. Required for migration and more customization
spring.jpa.hibernate.ddl-auto=update
# NOTE: Update for local data only. For production, no sensitive data in prod
spring.jpa.show-sql=true

# H2 Console Configuration (UI for DB)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console