package com.nikki.taskmanager.mapper;

import com.nikki.taskmanager.dto.TaskRequest;
import com.nikki.taskmanager.dto.TaskResponse;
import com.nikki.taskmanager.entity.Task;
import org.springframework.stereotype.Component;

@Component
/// NOTE: Can be autogenerated for prod projects
public class TaskMapper {

    public TaskResponse toResponse(Task task) {
        return TaskResponse.builder()
                .id(task.getId())
                .title(task.getTitle())
                .description(task.getDescription())
                .completed(task.getCompleted())
                .createdAt(task.getCreatedAt())
                .build();
    }

    public Task toEntity(TaskRequest taskRequest) {
        return Task.builder()
                .title(taskRequest.title())
                .description(taskRequest.description())
                .completed(taskRequest.completed() != null && taskRequest.completed())
                .build();
    }

    public void updateEntityFromRequest(Task task, TaskRequest taskRequest) {
        task.setTitle(taskRequest.title());
        task.setDescription(taskRequest.description());
        task.setCompleted(taskRequest.completed());
    }
}
